package com.efremandrei.matzpen

/** Russian copy for the dated 2026-09-30 snapshot and the programmatic UI. */
object RussianText {
    val questions = mapOf(
        "palestinian-state" to "Следует ли создать палестинское государство рядом с Израилем в рамках будущего соглашения?",
        "death-penalty" to "Следует ли Израилю законодательно ввести смертную казнь для террористов?",
        "haredi-draft" to "Следует ли обязать законом учащихся ультраортодоксальных иешив проходить службу и ввести личные санкции за уклонение?",
        "judicial-reform" to "Следует ли ограничить полномочия Верховного суда и усилить Кнессет и правительство в рамках предлагаемой судебной реформы?",
        "oct7-inquiry" to "Следует ли немедленно создать государственную комиссию по расследованию событий 7 октября?",
        "religion-state" to "Следует ли запустить общественный транспорт в шаббат и ввести гражданские браки в Израиле?",
        "gaza-control" to "Следует ли ЦАХАЛу сохранять контроль над безопасностью в Газе в ближайшие годы?",
        "lower-taxes" to "Следует ли снизить налоги, даже если государство будет предоставлять меньше общественных услуг?",
        "yeshiva-budgets" to "Следует ли увеличить финансирование иешив и ультраортодоксальных школ?",
        "price-controls" to "Следует ли расширить государственное регулирование цен на основные продукты питания?",
        "temple-mount" to "Следует ли разрешить еврейскую молитву на Храмовой горе, даже если это изменит статус-кво?",
        "settlements" to "Следует ли расширять поселения на Западном берегу?",
        "term-limits" to "Следует ли законодательно ограничить срок пребывания премьер-министра у власти?",
        "gaza-resettlement" to "Следует ли вновь создать еврейские поселения в Газе?",
        "food-imports" to "Следует ли открыть рынок для импорта продуктов питания и снизить пошлины, даже если это навредит израильскому сельскому хозяйству?",
        "lgbt-equality" to "Следует ли закрепить в законе полное равноправие ЛГБТК-людей, включая признание партнёрств?",
        "saudi-normalization" to "Следует ли Израилю пойти на уступки палестинцам, например заморозить строительство поселений, ради мирного соглашения с Саудовской Аравией?",
        "universal-service" to "Следует ли сделать военную или гражданскую службу обязательной для всех граждан Израиля, включая ультраортодоксов и арабов?"
    )

    val lists = mapOf(
        "likud" to "Ликуд", "beyachad" to "Беяхад", "yashar" to "Яшар!",
        "democrats" to "Демократы", "shas" to "ШАС", "utj" to "Объединённый иудаизм Торы",
        "rz" to "Религиозный сионизм и Зеут", "otzma" to "Оцма Йехудит",
        "amcha" to "Амха Исраэль", "beytenu" to "Наш дом Израиль",
        "joint" to "Объединённый список", "raam" to "РААМ", "noam" to "Ноам",
        "kachol" to "Кахоль-Лаван", "miluim" to "Резервисты и Экономическая партия",
        "haskel" to "Израиль прежде всего", "hakahal" to "Ха-Кахаль", "tzibur" to "Ультраортодоксальное общество",
        "tzomet" to "Цомет Бейт Исраэль", "batach" to "Бетах: социальная защита",
        "ahi" to "Ахи", "shutafut" to "Партнёрство для всех",
        "orot" to "Орот ха-Шахар", "byn" to "Вместе добьёмся успеха",
        "sharshar" to "Цепь любви и единства", "mishpat" to "Суд справедливости",
        "shema" to "Шема", "seder" to "Новый порядок", "britolam" to "Всемирный союз",
        "hatikun" to "Исправление", "gush" to "Библейский блок", "bitachon" to "Личная безопасность",
        "tzeva" to "Чёрный цвет", "tkuma" to "Ткума", "pirates" to "Пираты",
        "ganeden" to "Райский сад", "kolhanashim" to "Все женщины", "aniveata" to "Я и ты"
    )

    private val uiStrings = mapOf(
        "Quick" to "Быстрый",
        "Balanced" to "Средний",
        "Full" to "Полный",
        "Broad overview · ~3 min" to "Общий обзор · около 3 минут",
        "More detail · ~4 min" to "Подробнее · около 4 минут",
        "All issues · ~5 min" to "Все темы · около 5 минут",
        "Election Compass" to "Компас выборов",
        "Light" to "Светлая",
        "Dark" to "Тёмная",
        "Blue and white" to "Сине-белая",
        "Choose language" to "Выбрать язык",
        "Cancel" to "Отмена",
        "Unsure who to vote for?" to "За кого голосовать?",
        "Find your match with a quiz" to "Сравните взгляды в анкете",
        "Questionnaire length" to "Длина анкеты",
        "More answers broaden the comparison." to "Больше ответов расширяют сравнение.",
        "Source coverage still matters." to "Охват источников тоже важен.",
        "Review my answers" to "Посмотреть мои ответы",
        "Continue questionnaire" to "Продолжить анкету",
        "Start questionnaire" to "Начать анкету",
        "Private on this device." to "Данные остаются на этом устройстве.",
        "Answers save automatically." to "Ответы сохраняются автоматически.",
        "View my matches" to "Мои совпадения",
        "Explore" to "Обзор",
        "Browse election lists" to "Просмотреть списки",
        "About and sources" to "О приложении и источниках",
        "Election data" to "Данные о выборах",
        "26th Knesset · 27 October 2026" to "Кнессет 26-го созыва · 27 октября 2026 года",
        "Some lists are under court review." to "Статус некоторых списков рассматривается судом.",
        "Check official information before voting." to "Перед голосованием проверьте официальную информацию.",
        "Alignment is not a voting recommendation." to "Совпадение — не рекомендация голосовать.",
        "Your answers stay on this device." to "Ваши ответы остаются на этом устройстве.",
        "Original issue and context" to "Исходный вопрос и контекст",
        "Your view" to "Ваша позиция",
        "How much do you agree?" to "Насколько вы согласны?",
        "Strongly disagree" to "Совершенно не согласен/согласна",
        "Disagree" to "Не согласен/согласна",
        "Unsure / mixed" to "Не уверен(а) / смешанная позиция",
        "Agree" to "Согласен/согласна",
        "Strongly agree" to "Полностью согласен/согласна",
        "Choose an answer first" to "Сначала выберите ответ",
        "You can choose up to 3 priorities" to "Можно выделить до трёх важных тем",
        "Priorities count twice." to "Важные темы учитываются с двойным весом.",
        "Questions" to "Вопросы",
        "Close" to "Закрыть",
        "Previous" to "Назад",
        "Skip" to "Пропуск",
        "See matches" to "К результатам",
        "Next question" to "Далее",
        "Your policy matches" to "Ваши совпадения",
        "A few more answers will help." to "Ответьте ещё на несколько вопросов.",
        "Ranked matches start after 8 answers." to "Рейтинг появляется после восьми ответов.",
        "Answer another question" to "Ответить на следующий вопрос",
        "Scores use documented positions." to "Оценки основаны на подтверждённых позициях.",
        "How matching works" to "Как рассчитывается совпадение",
        "Ranked matches" to "Списки с рейтингом",
        "No list has enough documented positions for a rank with these answers." to "Для этих ответов ни у одного списка недостаточно подтверждённых позиций для рейтинга.",
        "Show fewer" to "Показать меньше",
        "Not enough evidence" to "Недостаточно данных",
        "You can inspect every list." to "Можно просмотреть каждый список.",
        "Missing positions are not disagreements." to "Отсутствие позиции не означает несогласия.",
        "More questions show more of your views." to "Дополнительные вопросы помогут учесть больше ваших взглядов.",
        "Source coverage still limits each score." to "Охват источников по-прежнему ограничивает каждую оценку.",
        "Edit answers" to "Изменить ответы",
        "Unranked" to "Без рейтинга",
        "Eligibility under court review" to "Допуск рассматривается судом",
        "Compare positions  ›" to "Сравнить позиции  ›",
        "unranked" to "без рейтинга",
        "After 8 answers, each documented list position is compared with your answer. A priority counts twice. The percentage averages agreement only where a qualifying source exists. Lists need at least 70% weighted evidence coverage to be ranked; ties share a rank. Unknown positions are not disagreements. This is policy alignment, not a voting recommendation." to "После восьми ответов каждый подтверждённый взгляд списка сравнивается с вашим ответом. Важная тема учитывается с двойным весом. Процент совпадения рассчитывается только по вопросам с подходящим источником. Для рейтинга требуется охват источников не менее 70% с учётом веса ответов; при равенстве оценок списки делят место. Неизвестная позиция не считается несогласием. Это сравнение взглядов, а не рекомендация голосовать.",
        "Done" to "Готово",
        "Election lists" to "Избирательные списки",
        "Search name or ballot letters" to "Поиск по названию или буквам в бюллетене",
        "All" to "Все",
        "Approved" to "Одобрены",
        "Under review" to "В суде",
        "No lists match this search." to "По запросу списки не найдены.",
        "Committee approved" to "Одобрен избирательной комиссией",
        "View positions and sources  ›" to "Позиции и источники  ›",
        "Committee approved list" to "Список одобрен избирательной комиссией",
        "List profile and status" to "Профиль и статус списка",
        "Unranked · not enough evidence" to "Без рейтинга · недостаточно данных",
        "Where views meet or differ" to "В чём взгляды совпадают и расходятся",
        "Broad alignment means the positions are at most one step apart on the answer scale." to "Близкие взгляды отличаются не более чем на один шаг шкалы ответов.",
        "Answer questions to compare your views with this list." to "Ответьте на вопросы, чтобы сравнить свои взгляды с этим списком.",
        "All issues" to "Все темы",
        "Agreement" to "Совпадения",
        "Differences" to "Различия",
        "Unknown" to "Нет данных",
        "No issues in this section." to "В этом разделе нет тем.",
        "Not answered" to "Нет ответа",
        "Documented list position" to "Подтверждённая позиция списка",
        "Source" to "Источник",
        "Open original Hebrew source" to "Открыть источник на иврите",
        "Open original source" to "Открыть исходный источник",
        "Back" to "Назад",
        "Against" to "Против",
        "Conditional or mixed" to "Частично или с оговорками",
        "For" to "За",
        "No qualifying source" to "Нет подходящего источника",
        "Platform" to "Программа",
        "Vote" to "Голосование",
        "Statement" to "Заявление",
        "About Election Compass" to "О компасе выборов",
        "An independent policy-alignment guide. It does not endorse a party or predict election outcomes." to "Независимый инструмент сравнения политических взглядов. Он не поддерживает ни один список и не прогнозирует результаты выборов.",
        "Your answers are stored only on this device. Public election content is downloaded by HTTPS; no answers or analytics are uploaded." to "Ответы хранятся только на этом устройстве. Общедоступные данные о выборах загружаются по HTTPS; ответы и данные об использовании не отправляются.",
        "Data and attribution" to "Данные и авторство",
        "Open dataset" to "Открытый набор данных",
        "Delete my answers" to "Удалить мои ответы",
        "Delete answers?" to "Удалить ответы?",
        "This deletes answers saved on this device. It cannot be undone." to "Ответы, сохранённые на этом устройстве, будут удалены. Отменить это действие нельзя.",
        "Delete" to "Удалить",
        "Home" to "Главная"
    )

    fun ui(english: String): String = uiStrings[english] ?: english
}
